### ISSUE TITLE
Show, Read instance to BoltCfg

### ISSUE THREAD

**Issue by odanoburu** [zmactep/hasbolt#23]
would you mind adding a `Read` and `Show` instance to `BoltCfg`? if not, do you know a simple way of having an user specify the configuration? (there are many options, so anything I could think of would involve lots of boilerplate or adding a dependency on a specialized library)

**Comment by zmactep** [comment]
Version [0.1.4.3](https://github.com/zmactep/hasbolt/releases/tag/0.1.4.3) fixes this.
