### ISSUE TITLE
ToJSON and FromJSON Instances to Node and Relationship Datatypes

### ISSUE THREAD

**Issue by manojgudi** [zmactep/hasbolt#4]
Is there a specific reason why hasbolt doesnt implement these instances? If you've just forgotten, I can send a pull request with these instances implemented.

**Comment by zmactep** [comment]
Hi @manojgudi!

Hasbolt doesn't depend on `aeson` or some other JSON library, as I thought that it is not a very common way to use **Node** and **Relationship**. I usually convert them to some domain-specific datatypes before sending REST request/response or something like this. So I consider this an application-side logic, not driver-side. What do you think about this?

**Comment by manojgudi** [comment]
Good point there!
Usually I see ToJSON/FromJSON instances for most of exposed datatypes (like here: [haskell-neo4j-client](https://github.com/asilvestre/haskell-neo4j-rest-client/blob/master/src/Database/Neo4j/Types.hs#L95)
For my use case, I can (and did) write small instances and I'm good to go. I will close this issue for now.
