### ISSUE TITLE
`Structure` is not exposed

### ISSUE THREAD

**Issue by nc6** [zmactep/hasbolt#7]
This makes it hard to do anything with a returned structure.

**Comment by zmactep** [comment]
Hi, @nc6 !

What kind of things are you going to do with `Structure`? I have not thought, that anyone needs it.

**Comment by nc6** [comment]
@zmactep  Sorry, for some reason I missed your reply. No particular plans for the structure, but since the `S` constructor to `Value` wraps it, currently anything inspecting `Value`s has to just ignore the structure.

**Comment by zmactep** [comment]
@nc6, thanks for the answer. Understood, ok, I'll fix it in the next version.
