### ISSUE TITLE
`def` Cannot be found

### ISSUE THREAD

**Issue by wjdhamilton** [zmactep/hasbolt#8]
Hello!

Since migrating from 0.1.1.2 to 0.1.2.1, the `def` function appears to have disappeared. What should we use instead?

Thanks for your help and the excellent package!

**Comment by wjdhamilton** [comment]
Aha! The answer is to import `Data.Default` as well as `Database.Bolt`

**Comment by dmateusp** [comment]
@wjdhamilton can I ask what led you to that conclusion? I am new to Haskell and could not find the solution on my own in documentation or using the ghci

**Comment by wjdhamilton** [comment]
Hi @dmateusp! I think I just worked it out from the source code, and a little deduction - it wasn't defined anywhere in `hasbolt`, so I knew it had to be in an imported package. I also realised that the `def` function had created a default object. So I type "haskell default" into Google and `Data.Default` came up as the first hit.

**Comment by aphorisme** [comment]
I had the same problem – what helped me was looking up the instances for `BltCfg` within the documentation. There you have, that it is an instance of `Default`.   : )

**Comment by wjdhamilton** [comment]
Ah, yes! That rings a bell actually.
