### ISSUE TITLE
Can't use Hasbolt with GrapheneDB

### ISSUE THREAD

**Issue by jameshaydon** [zmactep/hasbolt#9]
Trying to use Hasbolt to connect to a GrapheneDB database gives the error:
```
Network.Socket.recvBuf: resource vanished (Connection reset by peer)
```

I am using the following config:
```
demoUser :: BoltCfg
demoUser = def
  { user = "demo-user"
  , password = "..."
  , host = "hobby-jb...pl.dbs.graphenedb.com"
  , port = 24786
  }
```
Connecting with these credentials works fine with other Neo4j drivers.

**Comment by zmactep** [comment]
Hi @jameshaydon!

I'll try to reproduce the error. Last time I've tried Graphene was April, and then everything worked fine.

**Comment by albertoperdomo** [comment]
Hello @zmactep,

if you need any assistance from us at GrapheneBD in debugging please let us know.
Happy to help.

Alberto.

**Comment by zmactep** [comment]
Hello @albertoperdomo,

it's look like I don't have any instances for now. So, can I have any for a week or less to test the driver?

**Comment by albertoperdomo** [comment]
We have a free plan and you can create up to 10 sandbox instances for free (no need to enter a credit card).

On the sandbox databases the HTTP endpoint is not secured with TLS, so there is that difference, but the Bolt interface is terminated with TLS in the same for all plans.

I guess the free plan should work for testing? If not, let me know your account (perhaps email us at support at graphenedb to avoid sharing your email, so that we can add some credits for testing with paid plans.

**Comment by jameshaydon** [comment]
Hi @albertoperdomo, @zmactep !

I am encountering the problem on a sandbox plan, so I assume this would be good enough to debug the problem.

**Comment by zmactep** [comment]
Nice! Thank you :)

**Comment by jameshaydon** [comment]
Were you able to reproduce the issue @zmactep ?

**Comment by zmactep** [comment]
Hi @jameshaydon!

Yes but I cannot understand it yet. The server just breaks connection after I send a handshake with the protocol version. When I am trying to get a handshake answer from the server, the socket is already closed.

**Comment by jameshaydon** [comment]
Yeah, we are seeing the same behaviour then :/

**Comment by albertoperdomo** [comment]
Have you been able to figure out why this is happening?
We can confirm that other drivers are working fine.

Is it perhaps something specific to TLS or a particular version of Neo4j?

**Comment by zmactep** [comment]
So the problem is really in TLS support in Haskell network library. I hope I can fix it soon.

**Comment by albertoperdomo** [comment]
Thanks for the update! @zmactep

**Comment by jameshaydon** [comment]
Great thanks!

**Comment by zmactep** [comment]
So, I've switched to a great `connection` library, so now we can use TLS in `hasbolt` since version 0.1.2.2

**Comment by albertoperdomo** [comment]
@zmactep Sweet! Looking forward to @jameshaydon 's double check.

**Comment by zmactep** [comment]
It seems to work for me:
```haskell
λ import Database.Bolt
Prelude Database.Bolt
λ import Data.Default

Prelude Database.Bolt Data.Default
λ :set -XOverloadedStrings

Prelude Database.Bolt Data.Default
λ pipe <- connect $ def { user = "neo4j", password = "...", host = "hobby-...abpl.dbs.graphenedb.com", port = 24786, secure = True }

Prelude Database.Bolt Data.Default
λ run pipe $ query "MERGE (n:Person {name: \"Haskell User\"}) RETURN n.name as name"
[fromList [("name",T "Haskell User")]]
```

I'll leave the issue open until @jameshaydon check it too.
